# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75c9924a74568610e9aa96426c4b0c61dfa6903f0addada5fc9a0632a6fd5bae6b83298ae16fefe2dabbd3b4aa90c905bde9b464b8abfaaada3f7ec72eb64d0b

test:
  secret_key_base: 8263a388f0893a791ea89dbf5cebab10f21ec50a63db69edcbd81118ae9228055b004b6e8ac6cdb5c1ddb2c70f30841962c8ad1ef72f9b1b4e5e7dd23d2df2be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
